# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LRMultiClass_c <- function(X, y, beta_init, numIter = 50L, eta = 0.1, lambda = 1) {
    .Call(`_GroupHW_LRMultiClass_c`, X, y, beta_init, numIter, eta, lambda)
}

soft <- function(v, lambda) {
    .Call(`_GroupHW_soft`, v, lambda)
}

lasso <- function(Xtilde, Ytilde, beta, lambda) {
    .Call(`_GroupHW_lasso`, Xtilde, Ytilde, beta, lambda)
}

calculate_lambda_tp1 <- function(lambda_t) {
    .Call(`_GroupHW_calculate_lambda_tp1`, lambda_t)
}

fitLASSOstandardized_prox_Nesterov_c <- function(Xtilde, Ytilde, lambda, beta_start, eps = 0.0001, s = 0.01) {
    .Call(`_GroupHW_fitLASSOstandardized_prox_Nesterov_c`, Xtilde, Ytilde, lambda, beta_start, eps, s)
}

MyKmeans_c <- function(X, K, M, numIter = 100L) {
    .Call(`_GroupHW_MyKmeans_c`, X, K, M, numIter)
}

